Information:
  Title: vortex blogs
  Icon: icon.png
  Description: Writea is an open-source alternative for blogs, allowing for easy page configuration and ultimate flexibility.
  Link: github.com/vortexsinclair/writea
  Theme: Default

Connections:
  GitHub: vortexsinclair
  GitLab: 
  Bluesky: 
  Twitter:
  Mastodon:
  Medium:
  Twitch:
  YouTube:
