Information:
  Title: vortex blogs
  Icon: icon.png
  Description: my blogs!
  Link: github.com/vortexsinclair/writea
  Theme: twilightseafoam

Connections:
  GitHub: vortexsinclair
  GitLab: 
  Bluesky: 
  Twitter:
  Mastodon:
  Medium:
  Twitch:
  YouTube:
